---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Brickyard"
subtitle: "Service Directory"
logo: "assets/logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon
# footer: "Update this page at ..."

# Optional message
message:
  # url: https://....
  style: "is-info" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Notice"
  content: |
    Internal network access may be required for some services.
    Not all services may be listed, as services are still being added.

# Optional navbar
links: [] # Allows for navbar (dark mode, layout, and search) without any links
# links:
#   - name: "ansible"
#     icon: "fab fa-github"
#     url: "https://github.com/bastienwirtz/homer"
#     target: '_blank' # optionnal html a tag target attribute
#   - name: "Wiki"
#     icon: "fas fa-book"
#     url: "https://www.wikipedia.org/"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: Entertainment
    icon: "fas fa-tv"
    items:
      - name: "Plex"
        logo: "assets/tools/plex-pms-icon.png"
        subtitle: Movies, TV Shows, Live TV, DVR
        url: "http://192.168.0.20:32400/web/index.html"
        target: '_blank'

  - name: "Monitoring & Management"
    icon: "fas fa-heartbeat"
    items:
      - name: Portainer
        logo: "assets/tools/portainer.png"
        subtitle: Docker Container Management
        tag: "docker"
        url: "https://portainer.nuc.brickyard.whitestar.systems/"
        target: '_blank'
      - name: NMS
        logo: "assets/tools/LibreNSM-logo.png"
        subtitle: "Network Health"
        tag: "network"
        url: "http://nms.brickyard.whitestar.systems/"
        target: '_blank'
      - name: StatusCake
        logo: "assets/tools/status-cake.png"
        subtitle: "Uptime Monitoring"
        url: "https://app.statuscake.com/YourStatus.php"
        target: '_blank'
      # - name: "M/Monit"
      #   logo: "assets/tools/monit.png"
      #   subtitle: "Monitor & manage all monit enabled hosts"
      #   tag: "monit"
      #   url: "https://mmonit.com/monit/"
      # - name: "Grafana"
      #   logo: "assets/tools/grafana.png"
      #   subtitle: "Metric analytics & dashboards"
      #   url: "https://grafana.com/"
      # - name: "Kibana"
      #   logo: "assets/tools/elastic.png"
      #   subtitle: "Explore & visualize logs"
      #   tag: "elk"
      #   url: "https://www.elastic.co/products/kibana"
      # - name: "Website monitoring"
      #   logo: "assets/tools/pingdom.png"
      #   subtitle: "Pingdom public reports overview"
      #   tag: "CI"
      #   url: "https://www.pingdom.com/"

  - name: "Infrastructure"
    icon: "fas fa-server"
    items:
      - name: UDM Pro
        logo: "assets/tools/unifi-app-logo.png"
        subtitle: Network Management
        tag: "network"
        url: "https://ubnt.brickyard.whitestar.systems/"
        target: '_blank'
      - name: NAS
        logo: "assets/tools/synology_logo.png"
        subtitle: Network Attached Storage
        tag: "storage"
        url: "https://nas.brickyard.whitestar.systems/"
        target: '_blank'
      - name: Pi Hole
        logo: "assets/tools/pi-hole.png"
        subtitle: Local DNS and Ad Blocking
        tag: "dns"
        url: "http://pi.hole"
        target: '_blank'
      - name: UPS
        logo: "assets/tools/apc.png"
        tag: "power"
        subtitle: Remote Monitoring Portal - Schneider Electric
        url: "https://smartconnect.apc.com/"
        target: '_blank'

  - name: "Hosted"
    icon: "fas fa-globe-americas"
    items:
      - name: Home Assistant
        logo: "assets/tools/home-assistant.png"
        subtitle: Home Automation
        url: "https://home.whitestar.systems/"
        target: '_blank'
      - name: Tom's Blog
        logo: "assets/tools/ghost.png"
        tag: ghost
        url: "https://blog.tompaulus.com/"
        target: '_blank'
      - name: Tom's Gallery
        logo: "assets/tools/gallery.png"
        tag: koken
        url: "https://gallery.tompaulus.com/"
        target: '_blank'

  - name: "Externaly Hosted"
    icon: "fab fa-aws"
    items:
    - name: Tom's Homepage
      url: "https://tompaulus.com/"
      target: '_blank'
